// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYd7MK--AV4tdD8FhsGNABjGL5j3Hli8w',
    appId: '1:774210774147:web:4cebceb650ca8e745ae7b6',
    messagingSenderId: '774210774147',
    projectId: 'electivagrupo2-2a6ea',
    authDomain: 'electivagrupo2-2a6ea.firebaseapp.com',
    storageBucket: 'electivagrupo2-2a6ea.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuQcXbysXkj1MD_SrxUwD-f2ulsdUaqdQ',
    appId: '1:774210774147:android:8ea04d36bc594bc35ae7b6',
    messagingSenderId: '774210774147',
    projectId: 'electivagrupo2-2a6ea',
    storageBucket: 'electivagrupo2-2a6ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnrTqxp_ON-JqcqDaNC55YlKBJY776pnE',
    appId: '1:774210774147:ios:6d062b664eea447d5ae7b6',
    messagingSenderId: '774210774147',
    projectId: 'electivagrupo2-2a6ea',
    storageBucket: 'electivagrupo2-2a6ea.firebasestorage.app',
    iosBundleId: 'com.example.taller1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnrTqxp_ON-JqcqDaNC55YlKBJY776pnE',
    appId: '1:774210774147:ios:6d062b664eea447d5ae7b6',
    messagingSenderId: '774210774147',
    projectId: 'electivagrupo2-2a6ea',
    storageBucket: 'electivagrupo2-2a6ea.firebasestorage.app',
    iosBundleId: 'com.example.taller1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYd7MK--AV4tdD8FhsGNABjGL5j3Hli8w',
    appId: '1:774210774147:web:b0f0b7a7942e5b065ae7b6',
    messagingSenderId: '774210774147',
    projectId: 'electivagrupo2-2a6ea',
    authDomain: 'electivagrupo2-2a6ea.firebaseapp.com',
    storageBucket: 'electivagrupo2-2a6ea.firebasestorage.app',
  );
}
